### ISSUE TITLE
Use by instead of apply: Directions

### ISSUE THREAD

**Issue by Dacit** [isabelle-prover/isabelle-linter#4]
For the `use_by` lint, the reverse direction (use apply done instead of by) should be added.
Default config should not include either direction.

**Comment by TheMC47** [comment]
Detecting `by` commands is trivial, the tricky part is generating the replacement. I've thought of three ways we can go about it:

### 1. Render the AST
Basically transforming `Method` into a string. The tricky part: the AST ignores all irrelevant syntactic constructs (e.g. parentheses or spaces) since they're really just noise if we're trying to reason about the meaning of what's written. This makes reconstructing a string out the AST hard, because:
- we can't reconstruct exactly what the user wrote
- there are some non-trivial problems like deciding whether to wrap the combined methods in parentheses or not
### 2. Use a parser-combinator to extract the methods
This would work like `pRemoveApply` from `Use_By`. There's a catch: since `by` can have two methods, the parser needs to differentiate between them. This would mean dealing with nested parentheses (the parser would be something like `pMethod` that produces a list of tokens and doesn't care about precedence, so it's simpler than `pMethod` but still not trivial)
### 3. Extend the possible edits
Instead of just supporting replacement, we can make edits more sophisticated. In this particular case, the edit would look something like this:
```
Sequence(
  Insert("apply "),
  Copy(method1_range),
  Insert("\napply "),
  Copy(method2_range),
  Inset("\ndone\n"),
  Delete(by_range),
)
```

**Comment by TheMC47** [comment]
While working on #2, I noticed that `Force_Failure` also has the same problem, and that's why it's not generating an `Edit`
